# -*- coding: utf-8 -*-
"""basic_etl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6GB2Ovnznn843cHhwtHGgQfQ89ijPwG
"""

import requests
import pandas as pd

def sort(arr, key):
  n = len(arr)
  for i in range(n):
    for j in range(0,n-i-1):
      if arr[j][key] < arr[j+1][key]:
        arr[j], arr[j+1] = arr[j+1], arr[j]
  return arr

url = 'https://dummyapi.online/api/movies'
response = requests.get(url)
if response.status_code == 200:
  res_arr = response.json()
  sorted_res= sort(res_arr, 'rating')
  df = pd.DataFrame(sorted_res)
  df.to_excel('sorted_movies.xlsx', index=False)
  print("Data stores to stored_movies.xlsx")
  print(sorted_res)
  df = pd.DataFrame(sorted_res)
  df.to_excel('sorted_movies.xlsx', index=False)
  print("Data stores to stored_movies.xlsx")
else:
    print(':)')

